#pragma config(Sensor, dgtl1,  piston,         sensorDigitalOut)
#pragma config(Motor,  port1,           baseBottomLeft, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           baseTopLeft,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           torreFrontLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           torreBackLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leverArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           torreBackRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           torreFrontRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           baseTopRight,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          baseBottomRight, tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    //UserControlCodePlaceholderForTesting();

  	//base
  	motor[baseBottomLeft] = vexRT[Ch3] + vexRT[Ch4];
  	motor[baseTopLeft] = vexRT[Ch3] + vexRT[Ch4];
  	motor[baseBottomRight] = -vexRT[Ch3] + vexRT[Ch4];
  	motor[baseTopRight] = -vexRT[Ch3] + vexRT[Ch4];

  	//lift
  	if(vexRT[Btn6U] == 0 && vexRT[Btn6D] == 1){
  		motor(torreBackLeft) = 127;
  		motor(torreFrontLeft) = 127;
  		motor(torreBackRight) = -127;
  		motor(torreFrontRight) = -127;
  	}
  	else if(vexRT[Btn6D] == 0 && vexRT[Btn6U] == 1){
  		motor(torreBackLeft) = -127;
  		motor(torreFrontLeft) = -127;
  		motor(torreBackRight) = 127;
  		motor(torreFrontRight) = 127;
  	}
  	else{
  		motor(torreBackLeft) = 0;
  		motor(torreFrontLeft) = 0;
  		motor(torreBackRight) = 0;
  		motor(torreFrontRight) = 0;
  	}

  	//arm
  	if(vexRT[Btn5U] == 0 && vexRT[Btn5D] == 1){
  		motor(leverArm) = 127;
  	}
  	else if(vexRT[Btn5D] == 0 && vexRT[Btn5U] == 1){
  		motor(leverArm) = -127;
  	}
  	else{
  		motor(leverArm) = 0;
  	}

  	//piston pusher
  	if(vexRT(Btn7D) == 1){
  		SensorValue[piston] = 1;
  		wait1Msec(500);
  		SensorValue[piston] = 0;
  	}
  	else{
  		SensorValue[piston] = 0;
  	}

  }
}
