#pragma config(Sensor, dgtl1,  pistonMK,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  encoderLeft,    sensorRotation)
#pragma config(Sensor, dgtl3,  encoderRight,   sensorRotation)
#pragma config(Sensor, dgtl4,  limit,          sensorTouch)
#pragma config(Motor,  port1,           baseBottomLeftMK, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           baseTopLeftMK, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           torreFrontLeftMK, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           torreBackLeftMK, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leverArmMK,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           torreBackRightMK, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           torreFrontRightMK, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           baseTopRightMK, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          baseBottomRightMK, tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define META_KNIGHT 1
#define KIRBY 0

#include "MetaKnightMain.c"
