
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "AutonFiles.c"
#include "EncoderLogic.c"
#include "MovementLogic.c"

/////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////	 FUNCTIONS  	/////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////
///////	RESSETING ENCODERS	///////////////
/////////////////////////////////////////

//void resetEncoders()
//{
//	SensorValue[baseBottomLeft] = 0;
//	SensorValue[baseBottomRight] = 0;


//	getAbsLeft() = abs(SensorValue[baseBottomLeft]);
//	getAbsRight()  = abs(SensorValue[baseBottomRight]);

//}
/////////////////////////////////////////
///////	END RESETING ENCODERS	///////////
/////////////////////////////////////////


/////////////////////////////////////////
///////	RESETING Gyro	///////////////
/////////////////////////////////////////

void resetGyro()
{
	 SensorType[gyro] = sensorNone;
 		wait1Msec(1000);
 	 SensorType[gyro] = sensorGyro;
 		wait1Msec(1000);
}
/////////////////////////////////////////
///////	END RESETING Gyro	///////////
/////////////////////////////////////////

/////////////////////////////////////////
//////////////  FOWARD  /////////////////
/////////////////////////////////////////

void Foward(int forward)
{
	resetEncoders();

	while((getAbsLeft()<forward)&&(getAbsRight()<forward))
	{
				setAbsLeft(abs(SensorValue[baseBottomLeft]));
				setAbsRight(abs(SensorValue[baseBottomRight]));


		if(getAbsLeft() > getAbsRight())
		{
			motor[baseTopLeft]= -58;
    	motor[baseTopRight]= -60;
    	motor[baseBottomLeft]= -58;
    	motor[baseBottomRight]= -60;

		}
  	else if(getAbsLeft() < getAbsRight())
		{

			motor[baseTopLeft]= -60;
    	motor[baseTopRight]= -58;
    	motor[baseBottomLeft]= -60;
    	motor[baseBottomRight]= -58;

		}
		else if(getAbsLeft()==getAbsRight())
		{
			motor[baseTopLeft]= -60;
    	motor[baseTopRight]= -60;
    	motor[baseBottomLeft]= -60;
    	motor[baseBottomRight]= -60;
		}
	}
			motor[baseTopLeft]= 0;
    	motor[baseTopRight]= 0;
    	motor[baseBottomLeft]= 0;
    	motor[baseBottomRight]= 0;
}
/////////////////////////////////////////
///////////  END FOWARD   ///////////////
/////////////////////////////////////////





/////////////////////////////////////////
////////////  BACKWARD  /////////////////
/////////////////////////////////////////

void Backward(int backward)
{
	resetEncoders();

	while((getAbsLeft()<backward)&&(getAbsRight()<backward))
	{
				setAbsLeft(abs(SensorValue[baseBottomLeft]));
				setAbsRight(abs(SensorValue[baseBottomRight]));


		if(getAbsLeft() > getAbsRight())
		{
			motor[baseTopLeft]= 58;
    	motor[baseTopRight]= 60;
    	motor[baseBottomLeft]= 58;
    	motor[baseBottomRight]= 60;

		}
  	else if(getAbsLeft() < getAbsRight())
		{

			motor[baseTopLeft]= 60;
    	motor[baseTopRight]= 58;
    	motor[baseBottomLeft]= 60;
    	motor[baseBottomRight]= 58;

		}
		else if(getAbsLeft()==getAbsRight())
		{
			motor[baseTopLeft]= 60;
    	motor[baseTopRight]= 60;
    	motor[baseBottomLeft]= 60;
    	motor[baseBottomRight]= 60;
		}
	}
			motor[baseTopLeft]= 0;
    	motor[baseTopRight]= 0;
    	motor[baseBottomLeft]= 0;
    	motor[baseBottomRight]= 0;
		}




/////////////////////////////////////////
///////////  END BACKWARD   /////////////
/////////////////////////////////////////





/////////////////////////////////////////
//////////////  GRIGHT  /////////////////
/////////////////////////////////////////

void gRight(int gright)
{
	resetEncoders();

	while((getAbsLeft()<gright)&&(getAbsRight()<gright))
	{
			setAbsLeft(abs(SensorValue[baseBottomLeft]));
			setAbsRight(abs(SensorValue[baseBottomRight]));


		if(getAbsLeft() > getAbsRight())
		{
			motor[baseTopLeft]= -58;
    	motor[baseTopRight]= 60;
    	motor[baseBottomLeft]= -58;
    	motor[baseBottomRight]= 60;
		}
  	else if(getAbsRight() < getAbsLeft())
		{
			motor[baseTopLeft]= -60;
    	motor[baseTopRight]= 58;
    	motor[baseBottomLeft]= -60;
    	motor[baseBottomRight]= 58;
		}
		else if(getAbsLeft()==getAbsRight())
		{
			motor[baseTopLeft]= -60;
    	motor[baseTopRight]= 60;
    	motor[baseBottomLeft]= -60;
    	motor[baseBottomRight]= 60;
		}
	}
			motor[baseTopLeft]= 0;
    	motor[baseTopRight]= 0;
    	motor[baseBottomLeft]= 0;
    	motor[baseBottomRight]= 0;
}
/////////////////////////////////////////
///////////  END GRIGHT   ///////////////
/////////////////////////////////////////





/////////////////////////////////////////
//////////////  GLEFT  //////////////////
/////////////////////////////////////////

void gLeft(int gleft)
{
	resetEncoders();

	while((getAbsLeft()<gleft)&&(getAbsRight()<gleft))
	{
				setAbsLeft(abs(SensorValue[baseBottomLeft]));
				setAbsRight(abs(SensorValue[baseBottomRight]));


		if(getAbsLeft() > getAbsRight())
		{
			motor[baseTopLeft]= 58;
    	motor[baseTopRight]= -60;
    	motor[baseBottomLeft]= 58;
    	motor[baseBottomRight]= -60;

		}
  	else if(getAbsRight() < getAbsLeft())
		{
			motor[baseTopLeft]= 60;
    	motor[baseTopRight]= -58;
    	motor[baseBottomLeft]= 60;
    	motor[baseBottomRight]= -58;

		}
		else if(getAbsLeft()==getAbsRight())
		{
			motor[baseTopLeft]= 60;
    	motor[baseTopRight]= -60;
    	motor[baseBottomLeft]= 60;
    	motor[baseBottomRight]= -60;
		}
	}
			motor[baseTopLeft]= 0;
    	motor[baseTopRight]= 0;
    	motor[baseBottomLeft]= 0;
    	motor[baseBottomRight]= 0;
}
/////////////////////////////////////////
///////////  END GLEFT   ////////////////
/////////////////////////////////////////

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();

  	//base
    	motor[baseTopLeft]= vexRT[Ch3] + vexRT[Ch1];
    	motor[baseTopRight]= -vexRT[Ch3] + vexRT[Ch1];
    	motor[baseBottomLeft]= vexRT[Ch3] + vexRT[Ch1];
    	motor[baseBottomRight]= -vexRT[Ch3] + vexRT[Ch1];


    //arcadeControl(Ch3, Ch1);// didnt have to do anything found pre existing functions

    if(SensorValue(MGLeft) == 1 && SensorValue(MGRight) == 1){
   		 motor[baseMidLeft]= vexRT[Ch3] + vexRT[Ch1];
   		 motor[baseMidRight]= vexRT[Ch3] + vexRT[Ch1];
   	}


    //moving goal mech
   	if(SensorValue(MGLeft) == 0 && SensorValue(MGRight) == 0){

   		if(vexRT[Btn8R] == 1 && vexRT[Btn8L] == 0){
   		 motor[baseMidLeft]= -127;
   		 motor[baseMidRight]= 127;
   		}


   		if(vexRT[Btn8L] == 1 && vexRT[Btn8R] == 0){
   		 motor[baseMidLeft]= 127;
   		 motor[baseMidRight]= -127;
   		}

   		else {
   			 motor[baseMidLeft]= 0;
   			 motor[baseMidRight]= 0;
   		}

   	}

    //torre
    if((vexRT[Btn5U] == 1) && (vexRT[Btn5D] == 0)){
   	  motor(torreTop)= 127;
    	motor(torreBottom)= -127;
    }

    else if((vexRT[Btn5D] == 1) && (vexRT[Btn5U] == 0)){
    	motor(torreTop)= -127;
    	motor(torreBottom)= 127;
    }

    else {
    	motor(torreTop)= 0;
    	motor(torreBottom)= 0;
    }


    //chainBar pivot
    if(vexRT[Btn6U] == 1 && vexRT[Btn6D] == 0){
    	motor(chainPivotL)= 127;
    	motor(chainPivotR)= -127;
    }
    if(vexRT[Btn6D] ==1 && vexRT[Btn6U] == 0) {
    	motor(chainPivotL)= -127;
    	motor(chainPivotR)= 127;
    }


    //cone intake
    if(vexRT[Btn8D] == 1){
    	SensorValue[claw] = 1;
    }
    else {
    	SensorValue[claw] = 0;
    }

  }
}
