#pragma config(Sensor, dgtl10, MGLeft,         sensorDigitalOut)
#pragma config(Sensor, dgtl11, MGRight,        sensorDigitalOut)
#pragma config(Sensor, dgtl12, claw,           sensorDigitalOut)
#pragma config(Motor,  port1,           baseTopLeft,   tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port2,           baseTopRight,  tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           baseMidLeft,   tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           torreTLBL,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           torreTRBR,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           chainPivotR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           chainPivotL,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           baseMidRight,  tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           baseBottomLeft, tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          baseBottomRight, tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveRight)
